Final Fantasy[a] is a Japanese science fantasy anthology media franchise created by Hironobu Sakaguchi, and developed and owned by Square Enix (formerly Square). The franchise centers on a series of fantasy and science fantasy role-playing video games. The first game in the series was released in 1987, with 15 numbered main entries having been released to date and an upcoming 16th installment announced in 2020. The franchise has since branched into other video game genres such as tactical role-playing, action role-playing, massively multiplayer online role-playing, racing, third-person shooter, fighting, and rhythm, as well as branching into other media, including CGI films, anime, manga, and novels.

Final Fantasy primary installments are generally stand-alone anthology series of role playing games, each with different settings, plots and main characters, but the franchise is linked by several recurring elements, including game mechanics and recurring character names. Each plot centers on a particular group of heroes who are battling a great evil, but also explores the characters' internal struggles and relationships. Character names are frequently derived from the history, languages, pop culture, and mythologies of cultures worldwide. The mechanics of each game involve similar battle systems and maps.

The Final Fantasy video game series has been both critically and commercially successful. Several entries are regarded by many as some of the greatest video games, and the series as a whole selling more than 164 million software units worldwide, making it one of the best-selling video game franchises of all time. The series is well known for its innovation, visuals, such as the inclusion of full-motion videos (FMVs), photorealistic character models, and music by Nobuo Uematsu. It has popularized many features now common in role-playing games, also popularizing the genre as a whole in markets outside Japan.
Contents

    1 Media
        1.1 Games
            1.1.1 Main series
            1.1.2 Remakes, sequels and spin-offs
        1.2 Other media
            1.2.1 Film and television
            1.2.2 Other media
    2 Common elements
        2.1 Plot and themes
        2.2 Characters
        2.3 Gameplay
    3 Development and history
        3.1 Origin
        3.2 Design
        3.3 Graphics and technology
        3.4 Music
    4 Reception
        4.1 Rankings and aggregators
    5 Legacy
    6 See also
    7 Notes
    8 References
    9 External links

Media
Further information: List of Final Fantasy media
Games
Main article: List of Final Fantasy video games

The first installment of the series was released in Japan on December 18, 1987. Subsequent games are numbered and given a story unrelated to previous games, so the numbers refer to volumes rather than to sequels. Many Final Fantasy games have been localized for markets in North America, Europe, and Australia on numerous video game consoles, personal computers (PC), and mobile phones. Future installments will appear on seventh and eighth generation consoles. As of November 2016, the series includes the main installments from Final Fantasy to Final Fantasy XV, as well as direct sequels and spin-offs, both released and confirmed as being in development. Most of the older games have been remade or re-released on multiple platforms.[1]
Main series
Release timeline1987	Final Fantasy
1988	Final Fantasy II
1989
1990	Final Fantasy III
1991	Final Fantasy IV
1992	Final Fantasy V
1993
1994	Final Fantasy VI
1995–1996
1997	Final Fantasy VII
1998
1999	Final Fantasy VIII
2000	Final Fantasy IX
2001	Final Fantasy X
2002	Final Fantasy XI
2003–2005
2006	Final Fantasy XII
2007–2008
2009	Final Fantasy XIII
2010	Final Fantasy XIV (2010 video game)
2011–2012
2013	Final Fantasy XIV
2014–2015
2016	Final Fantasy XV
TBA	Final Fantasy XVI

Three Final Fantasy installments were released on the Nintendo Entertainment System (NES). Final Fantasy was released in Japan in 1987 and in North America in 1990.[2][3] It introduced many concepts to the console RPG genre, and has since been remade on several platforms.[3] Final Fantasy II, released in 1988 in Japan, has been bundled with Final Fantasy in several re-releases.[3][4][5] The last of the NES installments, Final Fantasy III, was released in Japan in 1990;[6] however, it was not released elsewhere until a Nintendo DS remake in 2006.[5]

The Super Nintendo Entertainment System (SNES) also featured three installments of the main series, all of which have been re-released on several platforms. Final Fantasy IV was released in 1991; in North America, it was released as Final Fantasy II.[7][8] It introduced the "Active Time Battle" system.[9] Final Fantasy V, released in 1992 in Japan, was the first game in the series to spawn a sequel: a short anime series, Final Fantasy: Legend of the Crystals.[3][10][11] Final Fantasy VI was released in Japan in 1994, titled Final Fantasy III in North America.[12]

The PlayStation console saw the release of three main Final Fantasy games. Final Fantasy VII (1997) moved away from the two-dimensional (2D) graphics used in the first six games to three-dimensional (3D) computer graphics; the game features polygonal characters on pre-rendered backgrounds. It also introduced a more modern setting, a style that was carried over to the next game.[3] It was also the second in the series to be released in Europe, with the first being Final Fantasy Mystic Quest. Final Fantasy VIII was published in 1999, and was the first to consistently use realistically proportioned characters and feature a vocal piece as its theme music.[3][13] Final Fantasy IX, released in 2000, returned to the series' roots by revisiting a more traditional Final Fantasy setting rather than the more modern worlds of VII and VIII.[3][14]

Three main installments, as well as one online game, were published for the PlayStation 2 (PS2).[15][16][17] Final Fantasy X (2001) introduced full 3D areas and voice acting to the series, and was the first to spawn a sub-sequel (Final Fantasy X-2, published in 2003).[18][19] The first massively multiplayer online role-playing game (MMORPG) in the series, Final Fantasy XI, was released on the PS2 and PC in 2002, and later on the Xbox 360.[20][21] It introduced real-time battles instead of random encounters.[21] Final Fantasy XII, published in 2006, also includes real-time battles in large, interconnected playfields.[22][23] The game is also the first in the main series to utilize a world used in a previous game, namely the land of Ivalice, which had previously featured in Final Fantasy Tactics and Vagrant Story.[24]

In 2009, Final Fantasy XIII was released in Japan, and in North America and Europe the following year, for PlayStation 3 and Xbox 360.[25][26] It is the flagship installment of the Fabula Nova Crystallis Final Fantasy series[27] and became the first mainline game to spawn two sub-sequels (XIII-2 and Lightning Returns).[28] It was also the first game released in Chinese and high definition along with being released on two consoles at once. Final Fantasy XIV, a MMORPG, was released worldwide on Microsoft Windows in 2010, but it received heavy criticism when it was launched, prompting Square Enix to rerelease the game as Final Fantasy XIV: A Realm Reborn, this time to the PlayStation 3 as well, in 2013.[29] Final Fantasy XV is an action role-playing game that was released for PlayStation 4 and Xbox One in 2016.[30][31] Originally a XIII spin-off titled Versus XIII, XV uses the mythos of the Fabula Nova Crystallis series, although in many other respects the game stands on its own and has since been distanced from the series by its developers.[32][33][34][35][36][37] The next mainline entry, Final Fantasy XVI, was announced in September 2020 for the PlayStation 5.[38]
Remakes, sequels and spin-offs
See also: List of Final Fantasy video games, List of Square Enix mobile games, and Category: Final Fantasy spin-offs

Final Fantasy has spawned numerous spin-offs and metaseries. Several are, in fact, not Final Fantasy games, but were rebranded for North American release. Examples include the SaGa series, rebranded The Final Fantasy Legend, and its two sequels, Final Fantasy Legend II and Final Fantasy Legend III.[39] Final Fantasy Mystic Quest was specifically developed for a United States audience, and Final Fantasy Tactics is a tactical RPG that features many references and themes found in the series.[40][41] The spin-off Chocobo series, Crystal Chronicles series, and Kingdom Hearts series also include multiple Final Fantasy elements.[39][42] In 2003, the Final Fantasy series' first sub-sequel, Final Fantasy X-2, was released.[43] Final Fantasy XIII was originally intended to stand on its own, but the team wanted to explore the world, characters and mythos more, resulting in the development and release of two sequels in 2011 and 2013 respectively, creating the series' first official trilogy.[28] Dissidia Final Fantasy was released in 2009, a fighting game that features heroes and villains from the first ten games of the main series.[44] It was followed by a prequel in 2011.[45] Other spin-offs have taken the form of subseries—Compilation of Final Fantasy VII, Ivalice Alliance, and Fabula Nova Crystallis Final Fantasy. Enhanced 3D remakes of Final Fantasy III and Final Fantasy IV were released in 2006 and 2007 respectively.[46][47] Final Fantasy VII Remake was released on the PlayStation 4 in 2020.[48]
Other media
Film and television
Final Fantasy in film1994	Final Fantasy: Legend of the Crystals
1995–2000
2001	Final Fantasy: The Spirits Within
Final Fantasy: Unlimited
2002–2004
2005	Final Fantasy VII: Advent Children
Last Order: Final Fantasy VII
2006–2015
2016	Kingsglaive: Final Fantasy XV
Brotherhood: Final Fantasy XV
2017	Final Fantasy XIV: Dad of Light
2018
2019	Final Fantasy XV: Episode Ardyn – Prologue

Square Enix has expanded the Final Fantasy series into various media. Multiple anime and computer-generated imagery (CGI) films have been produced that are based either on individual Final Fantasy games or on the series as a whole. The first was an original video animation (OVA), Final Fantasy: Legend of the Crystals, a sequel to Final Fantasy V. The story was set in the same world as the game, although 200 years in the future. It was released as four 30-minute episodes, first in Japan in 1994 and later in the United States by Urban Vision in 1998. In 2001, Square Pictures released its first feature film, Final Fantasy: The Spirits Within. The film is set on a future Earth invaded by alien life forms.[49] The Spirits Within was the first animated feature to seriously attempt to portray photorealistic CGI humans, but was considered a box office bomb and garnered mixed reviews.[49][50][51]

A 25-episode anime television series, Final Fantasy: Unlimited, was released in 2001 based on the common elements of the Final Fantasy series. It was broadcast in Japan by TV Tokyo and released in North America by ADV Films.

In 2005, Final Fantasy VII: Advent Children, a feature length direct-to-DVD CGI film, and Last Order: Final Fantasy VII, a non-canon OVA,[52] were released as part of the Compilation of Final Fantasy VII. Advent Children was animated by Visual Works, which helped the company create CG sequences for the games.[53] The film, unlike The Spirits Within, became a commercial success.[54][55][56][57] Last Order, on the other hand, was released in Japan in a special DVD bundle package with Advent Children. Last Order sold out quickly[58] and was positively received by Western critics,[59][60] though fan reaction was mixed over changes to established story scenes.[61]

Two animated tie-ins for Final Fantasy XV were announced at the Uncovered Final Fantasy XV fan and press event, forming part of a larger multimedia project dubbed the Final Fantasy XV Universe. Brotherhood: Final Fantasy XV is a series of five 10-to-20-minute-long episodes developed by A-1 Pictures and Square Enix detailing the backstories of the main cast. Kingsglaive: Final Fantasy XV, a CGI movie set for release prior to the game in Summer 2016, is set during the game's opening and follows new and secondary characters.[62][63][64][65] On February 26, 2019, Square Enix released a short anime, produced by Satelight Inc, called Final Fantasy XV: Episode Ardyn – Prologue on their YouTube channel which acts as the background story for the final piece of DLC for Final Fantasy XV giving insight into Ardyn's past.

Square Enix also released Final Fantasy XIV: Dad of Light, an 8-episode Japanese soap opera. It features a mix of live-action scenes and Final Fantasy XIV gameplay footage. It premiered in Japan on April 16, 2017, and became available worldwide via Netflix in September of the same year.

It was announced in June 2019 that Sony Pictures Television is working on a first ever live-action adaptation of the series with Hivemind and Square Enix. Jason F. Brown, Sean Daniel and Dinesh Shamdasani for Hivemind will be the producers while Ben Lustig and Jake Thornton will write for the series and will serve as executive producers.[66]
Other media

Several video games have either been adapted into or have had spin-offs in the form of manga and novels. The first was the novelization of Final Fantasy II in 1989, and was followed by a manga adaptation of Final Fantasy III in 1992.[67][68] The past decade has seen an increase in the number of non-video game adaptations and spin-offs. Final Fantasy: The Spirits Within has been adapted into a novel, the spin-off game Final Fantasy Crystal Chronicles has been adapted into a manga, and Final Fantasy XI has had a novel and manga set in its continuity.[69][70][71][72] Seven novellas based on the Final Fantasy VII universe have also been released. The Final Fantasy: Unlimited story was partially continued in novels and a manga after the anime series ended.[73] The Final Fantasy X and Final Fantasy XIII series have also had novellas and audio dramas released. Final Fantasy Tactics Advance has been adapted into a radio drama, and Final Fantasy: Unlimited has received a radio drama sequel.

A trading card game named the Final Fantasy trading card game is produced by Square Enix and Hobby Japan, first released Japan in 2012 with an English version in 2016.[74] The game has been compared to Magic: the Gathering, and a tournament circuit for the game also takes place.[75][76]
Common elements
Main article: Recurring elements in the Final Fantasy series

Although most Final Fantasy installments are independent, many gameplay elements recur throughout the series.[77][78] Most games contain elements of fantasy and science fiction and feature recycled names often inspired from various cultures' history, languages and mythology, including Asian, European, and Middle-Eastern.[79] Examples include weapon names like Excalibur and Masamune—derived from Arthurian legend and the Japanese swordsmith Masamune respectively—as well as the spell names Holy, Meteor, and Ultima.[78][79] Beginning with Final Fantasy IV, the main series adopted its current logo style that features the same typeface and an emblem designed by Japanese artist Yoshitaka Amano. The emblem relates to a game's plot and typically portrays a character or object in the story. Subsequent remakes of the first three games have replaced the previous logos with ones similar to the rest of the series.[78]
Plot and themes
Final Fantasy V is similar to the earlier games in the series, in that the heroes must attempt to retrieve crystals to save the world from an ancient evil.

The central conflict in many Final Fantasy games focuses on a group of characters battling an evil, and sometimes ancient, antagonist that dominates the game's world. Stories frequently involve a sovereign state in rebellion, with the protagonists taking part in the rebellion. The heroes are often destined to defeat the evil, and occasionally gather as a direct result of the antagonist's malicious actions.[3][79] Another staple of the series is the existence of two villains; the main villain is not always who it appears to be, as the primary antagonist may actually be subservient to another character or entity.[3] The main antagonist introduced at the beginning of the game is not always the final enemy, and the characters must continue their quest beyond what appears to be the final fight.[79]

Stories in the series frequently emphasize the internal struggles, passions, and tragedies of the characters, and the main plot often recedes into the background as the focus shifts to their personal lives.[23][80] Games also explore relationships between characters, ranging from love to rivalry.[3] Other recurring situations that drive the plot include amnesia, a hero corrupted by an evil force, mistaken identity, and self-sacrifice.[3][81][82] Magical orbs and crystals are recurring in-game items that are frequently connected to the themes of the games' plots.[79] Crystals often play a central role in the creation of the world, and a majority of the Final Fantasy games link crystals and orbs to the planet's life force. As such, control over these crystals drives the main conflict.[79][83] The classical elements are also a recurring theme in the series related to the heroes, villains, and items.[79] Other common plot and setting themes include the Gaia hypothesis, an apocalypse, and conflicts between advanced technology and nature.[79][81][84]
Characters
Further information: Character design of Final Fantasy and Template:Final Fantasy characters

The series features a number of recurring character archetypes. Most famously, every game since Final Fantasy II, including subsequent remakes of the original Final Fantasy, features a character named Cid. Cid's appearance, personality, goals, and role in the game (non-playable ally, party member, villain) vary dramatically. However, two characteristics many versions of Cid have in common are 1) being a scientist or engineer, and 2) being tied in some way to an airship the party eventually acquires. Every Cid has at least one of these two traits.

Biggs and Wedge, inspired by two Star Wars characters of the same name, appear in numerous games as minor characters, sometimes as comic relief.[23][78] The later games in the series feature several males with effeminate characteristics.[85][86] Recurring creatures include Chocobos, Moogles, and Cactuars.[87] Chocobos are large, often flightless birds that appear in several installments as a means of long-distance travel for characters. Moogles are white, stout creatures resembling teddy bears with wings and a single antenna. They serve different roles in games including mail delivery, weaponsmiths, party members, and saving the game. Cactuars are anthropomorphic cacti with haniwa-like faces presented in a running or dashing pose. They usually appear as recurring enemy units, and also as summoned allies or friendly non-player characters in certain titles. Chocobo and Moogle appearances are often accompanied by specific musical themes that have been arranged differently for separate games.[3][23][78]
Gameplay
Main article: Recurring elements in the Final Fantasy series § Gameplay

In Final Fantasy games, players command a party of characters as they progress through the game's story by exploring the game world and defeating enemies.[3][79] Enemies are typically encountered randomly through exploring, a trend which changed in Final Fantasy XI and Final Fantasy XII. The player issues combat orders—like "Fight", "Magic", and "Item"—to individual characters via a menu-driven interface while engaging in battles. Throughout the series, the games have used different battle systems. Prior to Final Fantasy XI, battles were turn-based with the protagonists and antagonists on different sides of the battlefield. Final Fantasy IV introduced the "Active Time Battle" (ATB) system that augmented the turn-based nature with a perpetual time-keeping system. Designed by Hiroyuki Ito, it injected urgency and excitement into combat by requiring the player to act before an enemy attacks, and was used until Final Fantasy X, which implemented the "Conditional Turn-Based" (CTB) system.[3][23][88] This new system returned to the previous turn-based system, but added nuances to offer players more challenge.[19][89] Final Fantasy XI adopted a real-time battle system where characters continuously act depending on the issued command.[90] Final Fantasy XII continued this gameplay with the "Active Dimension Battle" system.[91] Final Fantasy XIII's combat system, designed by the same man who worked on X,[92] was meant to have an action-oriented feel, emulating the cinematic battles in Final Fantasy VII: Advent Children. The latest installment to the franchise, Final Fantasy XV, introduces a new "Open Combat" system. Unlike previous battle systems in the franchise, the "Open Combat" system (OCS) allows players to take on a fully active battle scenario, allowing for free range attacks and movement, giving a much more fluid feel of combat. This system also incorporates a "Tactical" Option during battle, which pauses active battle to allow use of items.[93]

Like most RPGs, the Final Fantasy installments use an experience level system for character advancement, in which experience points are accumulated by killing enemies.[94][95][96][97] Character classes, specific jobs that enable unique abilities for characters, are another recurring theme. Introduced in the first game, character classes have been used differently in each game. Some restrict a character to a single job to integrate it into the story, while other games feature dynamic job systems that allow the player to choose from multiple classes and switch throughout the game. Though used heavily in many games, such systems have become less prevalent in favor of characters that are more versatile; characters still match an archetype, but are able to learn skills outside their class.[23][78][79]

Magic is another common RPG element in the series. The method by which characters gain magic varies between installments, but is generally divided into classes organized by color: "White magic", which focuses on spells that assist teammates; "Black magic", which focuses on harming enemies; "Red magic", which is a combination of white and black magic, "Blue magic", which mimics enemy attacks; and "Green magic" which focuses on applying status effects to either allies or enemies.[3][78][88] Other types of magic frequently appear such as "Time magic", focusing on the themes of time, space, and gravity; and "Summoning magic", which evokes legendary creatures to aid in battle and is a feature that has persisted since Final Fantasy III. Summoned creatures are often referred to by names like "Espers" or "Eidolons" and have been inspired by mythologies from Arabic, Hindu, Norse, and Greek cultures.[78][79]

Different means of transportation have appeared through the series. The most common is the airship for long range travel, accompanied by chocobos for travelling short distances, but others include sea and land vessels. Following Final Fantasy VII, more modern and futuristic vehicle designs have been included.[79]
Development and history
Origin
See also: Development of Final Fantasy (video game) and Development of Final Fantasy II
A man sitting in a chair and speaking in a microphone
Hironobu Sakaguchi, creator of the Final Fantasy series

In the mid-1980s, Square entered the Japanese video game industry with simple RPGs, racing games, and platformers for Nintendo's Famicom Disk System. In 1987, Square designer Hironobu Sakaguchi chose to create a new fantasy role-playing game for the cartridge-based NES, and drew inspiration from popular fantasy games: Enix's Dragon Quest, Nintendo's The Legend of Zelda, and Origin Systems's Ultima series. Though often attributed to the company allegedly facing bankruptcy, Sakaguchi explained that the game was his personal last-ditch effort in the game industry and that its title, Final Fantasy, stemmed from his feelings at the time; had the game not sold well, he would have quit the business and gone back to university.[98][99][100] Despite his explanation, publications have also attributed the name to the company's hopes that the project would solve its financial troubles.[99][101] In 2015, Sakaguchi explained the name's origin: the team wanted a title that would abbreviate to "FF", which would sound good in Japanese. The name was originally going to be Fighting Fantasy, but due to concerns over trademark conflicts with the roleplaying gamebook series of the same name, they needed to settle for something else. As the English word "Final" was well-known in Japan, Sakaguchi settled on that. According to Sakaguchi, any title that created the "FF" abbreviation would have done.[102]

The game indeed reversed Square's lagging fortunes, and it became the company's flagship franchise.[50][99] Following the success, Square immediately developed a second installment. Because Sakaguchi assumed Final Fantasy would be a stand-alone game, its story was not designed to be expanded by a sequel. The developers instead chose to carry over only thematic similarities from its predecessor, while some of the gameplay elements, such as the character advancement system, were overhauled. This approach has continued throughout the series; each major Final Fantasy game features a new setting, a new cast of characters, and an upgraded battle system.[5] Video game writer John Harris attributed the concept of reworking the game system of each installment to Nihon Falcom's Dragon Slayer series,[103] with which Square was previously involved as a publisher.[104] The company regularly released new games in the main series. However, the time between the releases of Final Fantasy XI (2002), Final Fantasy XII (2006), and Final Fantasy XIII (2009) were much longer than previous games. Following Final Fantasy XIV, Square Enix stated that it intended to release Final Fantasy games either annually or biennially. This switch was to mimic the development cycles of Western games in the Call of Duty, Assassin's Creed and Battlefield series, as well as maintain fan-interest.[105]
Design
See also: Category: Final Fantasy designers

For the original Final Fantasy, Sakaguchi required a larger production team than Square's previous games. He began crafting the game's story while experimenting with gameplay ideas. Once the gameplay system and game world size were established, Sakaguchi integrated his story ideas into the available resources. A different approach has been taken for subsequent games; the story is completed first and the game built around it.[106] Designers have never been restricted by consistency, though most feel each game should have a minimum number of common elements. The development teams strive to create completely new worlds for each game, and avoid making new games too similar to previous ones. Game locations are conceptualized early in development and design details like building parts are fleshed out as a base for entire structures.[77]

The first five games were directed by Sakaguchi, who also provided the original concepts.[79][107] He drew inspiration for game elements from anime films by Hayao Miyazaki; series staples like the airships and chocobos are inspired by elements in Castle in the Sky and Nausicaä of the Valley of the Wind, respectively.[108] Sakaguchi served as a producer for subsequent games until he left Square in 2001.[79][107] Yoshinori Kitase took over directing the games until Final Fantasy VIII,[109][110][111] and has been followed by a new director for each new game. Hiroyuki Ito designed several gameplay systems, including Final Fantasy V's "Job System", Final Fantasy VIII's "Junction System" and the Active Time Battle concept, which was used from Final Fantasy IV until Final Fantasy IX.[79][109] In designing the Active Time Battle system, Ito drew inspiration from Formula One racing; he thought it would be interesting if character types had different speeds after watching race cars pass each other.[112] Ito also co-directed Final Fantasy VI with Kitase.[79][109] Kenji Terada was the scenario writer for the first three games; Kitase took over as scenario writer for Final Fantasy V through Final Fantasy VII. Kazushige Nojima became the series' primary scenario writer from Final Fantasy VII until his resignation in October 2003; he has since formed his own company, Stellavista. Nojima partially or completely wrote the stories for Final Fantasy VII, Final Fantasy VIII, Final Fantasy X, and Final Fantasy X-2. He also worked as the scenario writer for the spin-off series, Kingdom Hearts.[113] Daisuke Watanabe co-wrote the scenarios for Final Fantasy X and XII, and was the main writer for the XIII games.[114][115][116]
Final Fantasy VI artwork by Yoshitaka Amano, who provided designs for much of the series

Artistic design, including character and monster creations, was handled by Japanese artist Yoshitaka Amano from Final Fantasy through Final Fantasy VI. Amano also handled title logo designs for all of the main series and the image illustrations from Final Fantasy VII onward.[107] Tetsuya Nomura was chosen to replace Amano because Nomura's designs were more adaptable to 3D graphics. He worked with the series from Final Fantasy VII through Final Fantasy X.[79][107] For Final Fantasy IX character designs were handled by Shukō Murase, Toshiyuki Itahana, and Shin Nagasawa.[117] Nomura is also the character designer of the Kingdom Hearts series, Compilation of Final Fantasy VII, and Fabula Nova Crystallis: Final Fantasy.[118] Other designers include Nobuyoshi Mihara and Akihiko Yoshida. Mihara was the character designer for Final Fantasy XI, and Yoshida served as character designer for Final Fantasy Tactics, the Square-produced Vagrant Story, and Final Fantasy XII.[41][119]
Graphics and technology

Because of graphical limitations, the first games on the NES feature small sprite representations of the leading party members on the main world screen. Battle screens use more detailed, full versions of characters in a side-view perspective. This practice was used until Final Fantasy VI, which uses detailed versions for both screens. The NES sprites are 26 pixels high and use a color palette of 4 colors. 6 frames of animation are used to depict different character statuses like "healthy" and "fatigued". The SNES installments use updated graphics and effects, as well as higher quality audio than in previous games, but are otherwise similar to their predecessors in basic design. The SNES sprites are 2 pixels shorter, but have larger palettes and feature more animation frames: 11 colors and 40 frames respectively. The upgrade allowed designers to have characters be more detailed in appearance and express more emotions. The first game includes non-player characters (NPCs) the player could interact with, but they are mostly static in-game objects. Beginning with the second game, Square used predetermined pathways for NPCs to create more dynamic scenes that include comedy and drama.[120]

In 1995, Square showed an interactive SGI technical demonstration of Final Fantasy VI for the then next generation of consoles. The demonstration used Silicon Graphics's prototype Nintendo 64 workstations to create 3D graphics.[120][121] Fans believed the demo was of a new Final Fantasy game for the Nintendo 64 console. 1997 saw the release of Final Fantasy VII for the Sony PlayStation.[121][122] The switch was due to a dispute with Nintendo over its use of faster but more expensive cartridges, as opposed to the slower and cheaper, but much higher capacity Compact Discs used on rival systems.[123][124] Final Fantasy VII introduced 3D graphics with fully pre-rendered backgrounds.[123][125] It was because of this switch to 3D that a CD-ROM format was chosen over a cartridge format.[123][126] The switch also led to increased production costs and a greater subdivision of the creative staff for Final Fantasy VII and subsequent 3D games in the series.[77]
Final Fantasy VIII, along with VII and IX, used pre-rendered backgrounds.

Starting with Final Fantasy VIII, the series adopted a more photo-realistic look.[127][128] Like Final Fantasy VII, full motion video (FMV) sequences would have video playing in the background, with the polygonal characters composited on top. Final Fantasy IX returned to the more stylized design of earlier games in the series, although it still maintained, and in many cases slightly upgraded, most of the graphical techniques used in the previous two games.[128] Final Fantasy X was released on the PlayStation 2, and used the more powerful hardware to render graphics in real-time instead of using pre-rendered material to obtain a more dynamic look; the game features full 3D environments, rather than have 3D character models move about pre-rendered backgrounds. It is also the first Final Fantasy game to introduce voice acting, occurring throughout the majority of the game, even with many minor characters.[19] This aspect added a whole new dimension of depth to the character's reactions, emotions, and development.[19][129]

Taking a temporary divergence, Final Fantasy XI used the PlayStation 2's online capabilities as an MMORPG.[130] Initially released for the PlayStation 2 with a PC port arriving six months later, Final Fantasy XI was also released on the Xbox 360 nearly four years after its original release in Japan.[131] This was the first Final Fantasy game to use a free rotating camera. Final Fantasy XII was released in 2006 for the PlayStation 2 and uses only half as many polygons as Final Fantasy X, in exchange for more advanced textures and lighting.[132][133] It also retains the freely rotating camera from Final Fantasy XI. Final Fantasy XIII and Final Fantasy XIV both make use of Crystal Tools, a middleware engine developed by Square Enix.[134][135]
Music
Main article: Music of the Final Fantasy series
Nobuo Uematsu, primary composer for the series

The Final Fantasy games feature a variety of music, and frequently reuse themes. Most of the games open with a piece called "Prelude", which has evolved from a simple, 2-voice arpeggio in the early games to a complex, melodic arrangement in recent installments.[23][78][100] Victories in combat are often accompanied by a victory fanfare, a theme that has become one of the most recognized pieces of music in the series. The basic theme that accompanies Chocobo appearances has been rearranged in a different musical style for each installment. A piece called "Prologue" (and sometimes "Final Fantasy"), originally featured in the first game, is often played during the ending credits.[78] Although leitmotifs are common in the more character-driven installments, theme music is typically reserved for main characters and recurring plot elements.[50]

Nobuo Uematsu was the primary composer of the Final Fantasy series until his resignation from Square Enix in November 2004.[50] Other notable composers who have worked on main entries in the series include Masashi Hamauzu, Hitoshi Sakimoto,[136][137] and Yoko Shimomura. Uematsu was allowed to create much of the music with little direction from the production staff. Sakaguchi, however, would request pieces to fit specific game scenes including battles and exploring different areas of the game world.[138] Once a game's major scenarios were completed, Uematsu would begin writing the music based on the story, characters, and accompanying artwork. He started with a game's main theme, and developed other pieces to match its style. In creating character themes, Uematsu read the game's scenario to determine the characters' personality. He would also ask the scenario writer for more details to scenes he was unsure about.[139] Technical limitations were prevalent in earlier games; Sakaguchi would sometimes instruct Uematsu to only use specific notes.[138] It was not until Final Fantasy IV on the SNES that Uematsu was able to add more subtlety to the music.[120]
Reception

Overall, the Final Fantasy series has been critically acclaimed and commercially successful, though each installment has seen different levels of success. The series has seen a steady increase in total sales; it sold over 10 million software units worldwide by early 1996,[140] more than 25 million units by 1999,[141] more than 33 million units and nearly $1 billion revenue (between $1.5–2.4 billion adjusted for inflation) by 2001,[142] 45 million units by August 2003, 63 million by December 2005, and 85 million by July 2008.[143][144][145] In June 2011, Square Enix announced that the series had sold over 100 million units,[146] and by March 2014, it had sold over 110 million units.[147] Its high sales numbers have ranked it as one of the best-selling video game franchises in the industry; in January 2007, the series was listed as number three, and later in July as number four.[50][148] As of 2019, the series had sold over 149 million units worldwide.[149] As of October 2021, the series has sold over 164 million units worldwide.[150]

Several games within the series have become best-selling games. At the end of 2007, the seventh, eighth, and ninth best-selling RPGs were Final Fantasy VII, Final Fantasy VIII, and Final Fantasy X respectively.[151] The original Final Fantasy VII has sold over 13.3 million copies worldwide,[152] earning it the position of the best-selling Final Fantasy game.[153] Within two days of Final Fantasy VIII's North American release on September 9, 1999, it became the top-selling video game in the United States, a position it held for more than three weeks.[154] Final Fantasy X sold over 1.4 million Japanese units in pre-orders alone, which set a record for the fastest-selling console RPG.[151][155] The MMORPG, Final Fantasy XI, reached over 200,000 active daily players in March 2006[156] and had reached over half a million subscribers by July 2007.[50] Final Fantasy XII sold more than 1.7 million copies in its first week in Japan.[157] By November 6, 2006—one week after its release—Final Fantasy XII had shipped approximately 1.5 million copies in North America.[158] Final Fantasy XIII became the fastest-selling game in the franchise,[159] and sold one million units on its first day of sale in Japan.[160] Final Fantasy XIV: A Realm Reborn, in comparison to its predecessor, was a runaway success, originally suffering from servers being overcrowded,[161] and eventually gaining over one million unique subscribers within two months of its launch.[162]

The series has received critical acclaim for the quality of its visuals and soundtracks.[50] In 1996, Next Generation ranked the series collectively as the 17th best game of all time, speaking very highly of its graphics, music and stories.[163] In 1999, Next Generation listed the Final Fantasy series as number 16 on their "Top 50 Games of All Time", commenting that, "By pairing state-of-the-art technology with memorable, sometimes shamelessly melodramatic storylines, the series has successfully outlasted its competitors [...] and improved with each new installation."[164] It was awarded a star on the Walk of Game in 2006, making it the first franchise to win a star on the event (other winners were individual games, not franchises). WalkOfGame.com commented that the series has sought perfection as well as having been a risk taker in innovation.[165] In 2006, GameFAQs held a contest for the best video game series ever, with Final Fantasy finishing as the runner-up to The Legend of Zelda.[166] In a 2008 public poll held by The Game Group plc, Final Fantasy was voted the best game series, with five games appearing in their "Greatest Games of All Time" list.[167]

Many Final Fantasy games have been included in various lists of top games. Several games have been listed on multiple IGN "Top Games" lists.[168][169][170][171][172][173] Twelve games were listed on Famitsu's 2006 "Top 100 Favorite Games of All Time", four of which were in the top ten, with Final Fantasy X and Final Fantasy VII coming first and second, respectively.[174] The series holds seven Guinness World Records in the Guinness World Records Gamer's Edition 2008, which include the "Most Games in an RPG Series" (13 main games, seven enhanced games, and 32 spin-off games), the "Longest Development Period" (the production of Final Fantasy XII took five years), and the "Fastest-Selling Console RPG in a Single Day" (Final Fantasy X).[151][175] The 2009 edition listed two games from the series among the top 50 consoles games: Final Fantasy XII at number 8 and Final Fantasy VII at number 20.[176] In 2018, Final Fantasy VII was inducted as a member of the World Video Game Hall of Fame.[177]

However, the series has garnered some criticism. IGN has commented that the menu system used by the games is a major detractor for many and is a "significant reason why they haven't touched the series."[23] The site has also heavily criticized the use of random encounters in the series' battle systems.[178][179] IGN further stated the various attempts to bring the series into film and animation have either been unsuccessful, unremarkable, or did not live up to the standards of the games.[11] In 2007, Edge criticized the series for a number of related games that include the phrase "Final Fantasy" in their titles, which are considered inferior to previous games. It also commented that with the departure of Hironobu Sakaguchi, the series might be in danger of growing stale.[50]

Several individual Final Fantasy games have garnered extra attention; some for their positive reception and others for their negative reception. Final Fantasy VII topped GamePro's "26 Best RPGs of All Time" list,[180] as well as GameFAQs "Best Game Ever" audience polls in 2004 and 2005.[181][182] Despite the success of Final Fantasy VII, it is sometimes criticized as being overrated. In 2003, GameSpy listed it as the seventh most overrated game of all time, while IGN presented views from both sides.[183][184] Dirge of Cerberus: Final Fantasy VII shipped 392,000 units in its first week of release, but received review scores that were much lower than that of other Final Fantasy games.[185][186][187] A delayed, negative review after the Japanese release of Dirge of Cerberus from Japanese gaming magazine Famitsu hinted at a controversy between the magazine and Square Enix.[188] Though Final Fantasy: The Spirits Within was praised for its visuals, the plot was criticized and the film was considered a box office bomb.[49][50][51][189] Final Fantasy Crystal Chronicles for the GameCube received overall positive review scores, but reviews stated that the use of Game Boy Advances as controllers was a big detractor.[122][190] The predominantly negative reception of the original version of Final Fantasy XIV caused then-president Yoichi Wada to issue an official apology during a Tokyo press conference, stating that the brand had been "greatly damaged" by the game's reception.[191]
Rankings and aggregators
Various video game publications have created rankings of the mainline Final Fantasy games. In the table below, the lower the number given, the better the game is in the view of the respective publication. By way of comparison, the ratings provided by Famitsu magazine and the review aggregator Metacritic are also given; in these rows, higher numbers indicate better reviews. Note that Metacritic ratings up until Final Fantasy VII largely represent retrospective reviews from online websites years after their initial release, rather than contemporary reviews from video game magazines at the time of their initial release. 
